// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3etfkSbV8mY5gbObMJt4cGcNbzrRAUOA',
    appId: '1:1006470390694:web:d1a824d5b719b303ac2567',
    messagingSenderId: '1006470390694',
    projectId: 'zavii-testes',
    authDomain: 'zavii-testes.firebaseapp.com',
    storageBucket: 'zavii-testes.appspot.com',
    measurementId: 'G-CRM4P4KHB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFuNyEyja4DXLPdjUplc0UXVHJgyv2EHw',
    appId: '1:1006470390694:android:06cb1a8184a8a5b0ac2567',
    messagingSenderId: '1006470390694',
    projectId: 'zavii-testes',
    storageBucket: 'zavii-testes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWf88SGkrgNzpTpEstKZzkMh5YJ7QLrTY',
    appId: '1:1006470390694:ios:89a4b165faafc703ac2567',
    messagingSenderId: '1006470390694',
    projectId: 'zavii-testes',
    storageBucket: 'zavii-testes.appspot.com',
    iosClientId: '1006470390694-fkdqj5uoqr21of0nrg8qqf351t8s5oed.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWf88SGkrgNzpTpEstKZzkMh5YJ7QLrTY',
    appId: '1:1006470390694:ios:89a4b165faafc703ac2567',
    messagingSenderId: '1006470390694',
    projectId: 'zavii-testes',
    storageBucket: 'zavii-testes.appspot.com',
    iosClientId: '1006470390694-fkdqj5uoqr21of0nrg8qqf351t8s5oed.apps.googleusercontent.com',
    iosBundleId: 'com.example.baseApp',
  );
}
