name: core
description: Module togheter features
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  commons_dependencies:
    path: '../commons_dependencies'
  splash_module:
    path: '../splash_module'
  sign_up_module:
    path: '../sign_up_module'
  commons_shared:
    path: '../commons_shared'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
